version: '2'
services:
  storage:
    build: ./docker/development/storage
    entrypoint: /bin/true
    volumes:
      - ./:/var/www/html
    network_mode: "bridge"

  phpfpm:
    build: ./docker/development/php
    links:
      - mysql:mysql
    expose:
      - "9000"
    volumes_from:
      - storage
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 120s
    command: php-fpm
    network_mode: "bridge"

  nginx:
    build: ./docker/development/nginx
    links:
      - phpfpm:phpfpm
    expose:
      - "80"
    volumes:
      - ./docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf
    volumes_from:
      - storage
    environment:
      VIRTUAL_HOST: mojtim.local
    network_mode: "bridge"

  mysql:
    build: ./docker/development/mysql
    ports:
      - "33090:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mojtim
      MYSQL_DATABASE: mojtim
      MYSQL_USER: mojtim
      MYSQL_PASSWORD: mojtim
    network_mode: "bridge"
